services:
  app:
    build: .
    container_name: docker-tutorial-example2-container-new
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    volumes:
      - .:/example2